[versions]
compose-bom = "2022.11.00"
activity-compose = "1.6.1"
ui-tooling-preview = "1.3.1"
glide-compose = "1.0.0-alpha.1"
material = "1.2.0"
android-application = "7.4.2"
android-library = "7.4.2"
kotlin-android = "1.7.0"
kotlin-jvm = "1.7.0"
kotlin = "1.7.20"
junit = "4.13.2"
androidx-junit = "1.1.5"
androidx-espresso-core = "3.5.1"
core-ktx = "1.7.0"
appcompat = "1.4.1"
hilt = "2.44"
retrofit = "2.9.0"
okHttp = "4.10.0"
coroutine = "1.6.4"
java-inject = "1"

[libraries]

compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "compose-bom" }
activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "activity-compose" }
ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview", version.ref = "ui-tooling-preview" }
material = { group = "androidx.compose.material", name = "material", version.ref = "material" }
foundation = { group = "androidx.compose.foundation", name = "foundation" }
core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "core-ktx" }
appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }

hilt-android = { group = "com.google.dagger", name = "hilt-android", version.ref = "hilt" }
hilt-compiler = { group = "com.google.dagger", name = "hilt-compiler", version.ref = "hilt" }

retrofit = { group = "com.squareup.retrofit2", name = "retrofit", version.ref = "retrofit" }
okHttp = { group = "com.squareup.okhttp3", name = "okhttp", version.ref = "okHttp" }
coroutine = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-core", version.ref = "coroutine" }
java-inject = { group = "javax.inject", name = "javax.inject", version.ref = "java-inject" }

glide = { group = "com.github.bumptech.glide", name = "compose", version.ref = "glide-compose" }

junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "androidx-junit" }
androidx-espresso = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "androidx-espresso-core" }

[plugins]
com-android-application = { id = "com.android.application", version.ref = "android-application" }
com-android-library = { id = "com.android.library", version.ref = "android-library" }
org-jetbrains-kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin-android" }
org-jetbrains-kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin-jvm" }

kotlin-kapt = { id = "org.jetbrains.kotlin.kapt", version.ref = "kotlin" }
hilt-plugin = { id = "com.google.dagger.hilt.android", version.ref = "hilt" }


